fix warnings found when running check/doc commands
tower-rs/tower pull request #779
Opened 2024-07-22 11:55 UTC by GlenDC

2024-07-22 12:02 UTC, GlenDC commented
Due to our MSRV check it does require a lower bound on the minor version of `futures` dep, FYI @tobz .

2024-07-22 13:14 UTC, tobz requested changes

2024-07-22 13:14 UTC, tobz commented on examples/Cargo.toml
> +futures = "^0.3.22"
You can drop the leading caret. That's already the implicit behavior of Cargo's version resolver.

2024-07-23 13:39 UTC, tobz approved these changes

2024-07-23 14:55 UTC, merged